pytech_bookstore/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('store/', include('store.urls', namespace='store')),
]

store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('', views.index, name='index'),
    path('authors/', views.AuthorListView.as_view(), name='authors_list'),
    path('books/', views.BookListView.as_view(), name='books_list'),
    path('genres/', views.GenreListView.as_view(), name='genres_list'),
    path('contact/', views.contact, name='contact'),
    path('authors/create/', views.AuthorCreateView.as_view(), name='author_create'),
]

store/models.py
from django.db import models
from django.utils.text import slugify

# Create your models here.

GENRE_CHOICES = (
    ('0', 'None'),
    ('1', 'Romance'),
    ('2', 'Sci-Fi'),
    ('3', 'Fantasy'),
    ('4', 'Drama'),
    ('5', 'Poetry'),
    ('6', 'Horror'),
)


class Genre(models.Model):
    name = models.CharField(max_length=200, unique=True)

    class Meta:
        ordering = ["name",]

    def __str__(self):
        return str(self.name)

class Author(models.Model):
    first_name = models.CharField(max_length=100, null=True)
    last_name = models.CharField(max_length=100, null=True)
    email = models.EmailField(max_length=100, unique=True, db_index=True)
    # genre = models.ManyToManyField(Genre)
    date_of_birth = models.DateField(null=False)
    created_on = models.DateField(auto_now_add=True)
    last_updated = models.DateTimeField(auto_now=True)
    number_of_books = models.IntegerField()

    class Meta:
        ordering = ['last_name', 'first_name']
        constraints = [
            models.UniqueConstraint(fields=['first_name', 'last_name'], name='author_names_unique'),
        ]
        db_table = "author" # appname_modelname
        verbose_name = "Author"
        verbose_name_plural = "Authors"
        get_latest_by = "created_on"
        indexes = [
            models.Index(fields=['last_name', 'first_name'], name='full_name_idx'),
            # models.Index(fields=['genre'], name='genre_idx'),
        ]

    def __str__(self):
        return str(self.first_name + ' ' + self.last_name)


class Book(models.Model):
    title = models.CharField(max_length=200, null=False, unique=True)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True, related_name="books")
    summary = models.TextField(max_length=1000, null=False)
    isbn = models.CharField(max_length=13, unique=True, help_text='13 character string - ISBN Number')
    genre = models.ManyToManyField(Genre)
    date_of_publishing = models.DateField()
    in_stock = models.BooleanField(default=True)
    price = models.DecimalField(max_digits=5, decimal_places=2, null=False)
    slug = models.SlugField()
    discount = models.IntegerField()

    class Meta:
        ordering = ["title", "author",]

    def save(self, *args, **kwargs):
        self.slug = slugify(str(self.title))
        self.discount = self.price // 5
        super(Book, self).save(*args, **kwargs)
    
    def __str__(self) -> str:
        return str(self.title)


class StoreManager(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)

    def __str__(self) -> str:
        return str(self.first_name + ' ' + self.last_name )


class StoreLocation(models.Model):
    store_name = models.CharField(max_length=100)
    store_manager = models.OneToOneField(StoreManager, on_delete=models.SET_NULL, null=True)

    def __str__(self) -> str:
        return str(self.store_name )
    

class Contact(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField(max_length=200)
    phone_number = models.CharField(max_length=20)
    message = models.TextField()

store/forms.py
from django import forms
from .models import Book, Author


class ContactForm(forms.Form):
    name = forms.CharField(max_length=200)
    email = forms.EmailField(max_length=200)
    phone_number = forms.CharField(max_length=200)
    message = forms.CharField(widget=forms.Textarea(attrs={"rows": "10"}))


class BookForm(forms.ModelForm):
    dummy_field = forms.CharField(max_length=10)
    class Meta:
        model = Book
        fields = ['title', 'author', 'summary', 'isbn', 'genre', 'date_of_publishing', 'in_stock', 'price']
        exclude = ['discount', 'slug']


class AuthorForm(forms.ModelForm):
    date_of_birth = forms.DateField(widget=forms.DateInput(format="%Y-%m-%d", attrs={"type": "date"}))

    class Meta:
        model = Author
        exclude = ["created_on", "last_updated"]

store/views.py
from typing import Any
from django.http import HttpResponse
from .models import Author, Book, Genre, StoreManager, StoreLocation, Contact
from django.views import View
from django.urls import reverse
from django.shortcuts import render, redirect
from .forms import ContactForm, BookForm, AuthorForm
from django.views.generic.edit import FormView
from django.views.generic import TemplateView


def index(request):
    num_of_book = Book.objects.all().count()
    return render(request, "store/index.html", {"num_of_book": num_of_book})


class AuthorListView(View):

    def get(self, request):
        authors = Author.objects.all()

        return render(request, "store/author_list.html", {"authors": authors})
    

class AuthorCreateView(FormView):
    template_name = "store/create_author.html"
    form_class = AuthorForm
    success_url = "/store/authors/"

    def form_valid(self, form):
        form.save()
        return super(AuthorCreateView, self).form_valid(form)


class BookListView(View):

    def get(self, request):
        books = Book.objects.all()
        form = BookForm()
        return render(request, 'store/book_list.html', {
            "books": books, "form": form
        })
    def post(self, request):
        form = BookForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('store:book_list')
        else:
            return render(request, "store/book_list.html", {
                "form": form, "books": books
                })   
    

# class GenreListView(View):

#     def get(self, request):
#         genres = Genre.objects.all()
#         content = ''

#         for genre in genres:
#             new_genre = f"<li>{genre}</li>"
#             content += new_genre
        
#         return HttpResponse(content)

class GenreListView(TemplateView):
    template_name = "store/genre_list.html"
    
    def get_context_data(self, *args, **kwargs):
        context = super(GenreListView, self).get_context_data(*args, **kwargs)
        context['genres'] = Genre.objects.all()
        context['random'] = "Just some random text"
        return context


def contact(request):
    # create the form object/instance
    form = ContactForm()
    # send the form as context to the template
    if request.method == "GET":
        return render(request, "store/contact.html", {'form': form})

    # Saving to DB
    elif request.method == "POST":
        # receive the form using a POST request
        form = ContactForm(request.POST)

        # Validate the form inputs
        if form.is_valid():
            # Save inputs to DB
            new_contact = Contact(name=form.cleaned_data['name'], email=form.cleaned_data['email'],
                                phone_number=form.cleaned_data['phone_number'], message=form.cleaned_data['message'])
            new_contact.save()
            return redirect('store:index')
        else:
            return render(request, 'store/contact.html', {"form": form})


    

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
        {% block title %}

        {% endblock %}

		<!-- meta -->
		<meta charset="UTF-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1">

	    <!-- css -->
		<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
		<link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}">
		<link rel="stylesheet" href="{% static 'css/pace.css' %}">
	    <link rel="stylesheet" href="{% static 'css/custom.css' %}">

	    <!-- js -->
	    <script src="js/jquery-2.1.3.min.js"></script>
	    <script src="js/bootstrap.min.js"></script>
	    <script src="js/pace.min.js"></script>
	    <script src="js/modernizr.custom.js"></script>
	</head>

    <body id="page">
		<div class="container">	
			<header id="site-header">
				<div class="row">
					<div class="col-md-4 col-sm-5 col-xs-8">
						<div class="logo">
							<h1><a href="#"><b>Pytech</b> Bookstore</a></h1>
						</div>
					</div><!-- col-md-4 -->
					<div class="col-md-8 col-sm-7 col-xs-4">
						<nav class="main-nav" role="navigation">
							<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  								<ul class="nav navbar-nav navbar-right">
    								<li class="cl-effect-11"><a href="{% url 'store:index' %}" data-hover="Home">Home</a></li>
    								<li class="cl-effect-11"><a href="{% url 'store:books_list' %}" data-hover="Store">Store</a></li>
    								<li class="cl-effect-11"><a href="{% url 'store:contact' %}" data-hover="Contact">Contact</a></li>
  								</ul>
							</div><!-- /.navbar-collapse -->
						</nav>
					</div><!-- col-md-8 -->
				</div>
			</header>
		</div>

        {% block content %}

        {% endblock %}

        <footer id="site-footer">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<p class="copyright">&copy; 2024 Pytech</p>
					</div>
				</div>
			</div>
		</footer>
		<script src="js/script.js"></script>
		
	</body>
</html>

templates/store/author_list.html
{% extends "base.html" %}

{% block content %}
        <div class="content-body">
			<div class="container">
				<div class="row">
					<main class="col-md-12">
						<div class="widget widget-recent-posts">		
							<h3 class="widget-title">All the authors in our store</h3>		
							<ul>
								{% for author in authors %}
								<li>
									<a href="#">{{ author }}</a>
								</li>
								{% endfor %}
							</ul>
						</div>
					</main>
				</div>
			</div>
		</div>

{% endblock %}

templates/store/book_list.html
{% extends 'base.html' %}

{% block content %}
        <div class="content-body">
			<div class="container">
				<div class="row">
					<main class="col-md-8">
						{% for book in books %}
						<article class="post post-1">
							<header class="entry-header">
								<h1 class="entry-title">
									<a href="#">{{book.title | lower }}</a>
								</h1>
								<div class="entry-meta">
									{% if book.genre.all %}
										{% for genre in book.genre.all %}
										<span class="post-category"><a href="#">{{ genre }}</a></span>
										{% endfor %}
									{% else %}
										<span class="post-category"><a href="#">No Genres</a></span>
									{% endif %}
			
									<span class="post-date"><a href="#">{{ book.date_of_publishing | date:"Y D d M"}}</a></span>
			
									<span class="post-author"><a href="#">{{ book.author }}</a></span>
			
									<span class="comments-link"><a href="#">4 Comments</a></span>
								</div>
							</header>
							<div class="entry-content clearfix">
								<div class="read-more cl-effect-14">
									<a href="#" class="more-link">Read summary <span class="meta-nav">→</span></a>
								</div>
							</div>
						</article>
						{% endfor %}
						<form method="post">
							{% csrf_token %}
							{{ form.as_p }}
							<input type="Submit" value="Save">
						</form>
					</main>
                    <aside class="col-md-4">
						<div class="widget widget-recent-posts">		
							<h3 class="widget-title">A bit more in our store</h3>		
							<ul>
								<li>
									<a href="#">Authors</a>
								</li>
								<li>
									<a href="#">Books</a>
								</li>
								<li>
									<a href="#">Genres</a>
								</li>
							</ul>
						</div>
					</aside>
				</div>
			</div>
		</div>

{% endblock %}

templates/store/contact.html
{% extends 'base.html' %}

{% block content %}
    <h2>Contact Us</h2>
    <form method="post">
        {% csrf_token %}
        {{form}}
        <input type="Submit" value="Save">
    </form>
{% endblock %}

templates/store/create_author.html
{% extends 'base.html' %}

{% block content %}

<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-12">
                <form method="post">
                    {% csrf_token %}
                    <p> {{form.first_name.label}} - {{ form.first_name }}</p>
                    <p> {{form.last_name.label}} - {{ form.last_name }}</p>
                    <p> {{form.email.label}} - {{ form.email }}</p>
                    <p> {{form.date_of_birth.label}} - {{ form.date_of_birth }}</p>
                    <p> {{form.number_of_books.label}} - {{ form.number_of_books }}</p>
                    <input type="Submit" value="Save">
                </form>
            </main>
        </div>
    </div>
</div>

{% endblock %}

templates/store/genre_list.html
{% extends "base.html" %}

{% block content %}
        <div class="content-body">
			<div class="container">
				<div class="row">
					<main class="col-md-12">
						<div class="widget widget-recent-posts">		
							<h3 class="widget-title">All the genres in our store</h3>	
                            <p>{{ random }}</p>	
							<ul>
								{% for genre in genres %}
								<li>
									<a href="#">{{genre}}</a>
								</li>
                                {% endfor %}
							</ul>
						</div>
					</main>
				</div>
			</div>
		</div>
{% endblock %}

templates/store/index.html
{% extends "base.html" %}

{% block title %}

<title>Pytech Bookstore</title> 

{% endblock %}

{% block content %}
		<div class="content-body">
			<div class="container">
				<div class="row">
					<main class="col-md-12">
						<h1 class="page-title">Welcome to the Pytech Bookstore</h1>
						<article class="post">
							<div class="entry-content clearfix">
								<p>
									Have you ever wondered how many books have been published? 
									Although it’s impossible for us to come up with an exact number, 
									according to Google, they believe it is around 130 million books! 
									Head on over to our store to explore all the possibilities that books can give us.
								</p>
								<p>
									Number of books in stock: {{ num_of_book }}
								</p>								
								<div class="height-40px"></div>				
								<div class="read-more cl-effect-14">
									<a href="{% url 'store:books_list' %}" class="more-link">Check out our store<span class="meta-nav">→</span></a>
								</div>
								<div class="height-40px"></div>
							</div>
						</article>
					</main>
				</div>
			</div>
		</div>
{% endblock %}